name: GitHub-Profile-Summary-Cards

on:
  schedule:
    # runs once every 24 hours
    - cron: "0 0 * * 1,3,5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.summary_gh_actions }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          # UTC_OFFSET is optional, default is 0. Set to your timezone offset, e.g. 5.5 for IST
          UTC_OFFSET: 5.5
          AUTO_PUSH: true
